name: Deploy to EC2 on push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Node App to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy and run Docker container
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            docker pull anasmhd/jiitak-node-app
            docker stop $(docker ps -q) || true
            docker rm $(docker ps -a -q) || true
            docker run -d -p 80:3000 anasmhd/jiitak-node-app
          EOF
